### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by ymoisan** [airbusgeo/cogger#10]
Hi Thomas.  Any plans for a Docker image ?

**Comment by tbonfort** [comment]
I don't think there's any advantage of providing docker images given we already ship a self-contained binary. If you really need one it is trivial to implement:
```dockerfile
FROM alpine:3 AS builder
RUN apk add unzip
WORKDIR /
ADD https://github.com/airbusgeo/cogger/releases/download/v0.0.7/cogger_0.0.7_linux_amd64.zip /
RUN unzip /cogger_0.0.7_linux_amd64.zip

FROM scratch
COPY --from=builder /cogger /cogger
ENTRYPOINT ["/cogger"]
```

**Comment by ymoisan** [comment]
Thanx.  That'll be useful in a [container-based workflow engine](https://argoproj.github.io/argo-workflows/).
