### ISSUE TITLE
Support of the separated mask *.msk file ?

### ISSUE THREAD

**Issue by mdouchin** [airbusgeo/cogger#11]
Hi,

Thanks a lot for this amazing tool !
I have just converted a 15Go ECW to GeoTiff with GDAL. To be able to use the `YCBCR` jpeg optimization, I have been "forced" to remove the 4th transparency band of the ECW. I used the `-mask 4` to keep the transparency and avoid to have a big black rectangle.

`gdalinfo` against the ecw gives: https://paste.sh/DAITkjGJ#P0ui5RBQaEDpDP0vQnHSWyny

My use of gdal_translate & gdaladdo:

```bash
# convert ecw to tif
gdal_translate -a_srs EPSG:2154 -r nearest -co COMPRESS=JPEG -co JPEG_QUALITY=60 --config INTERLEAVE PIXEL -co PHOTOMETRIC=YCBCR -b 1 -b 2 -b 3 -mask 4 -co TILED=YES -co BIGTIFF=YES -co BLOCKXSIZE=512 -co BLOCKYSIZE=512 --config GDAL_CACHEMAX 500 --config GDAL_MAX_DATASET_POOL_SIZE 1014 -co NUM_THREADS=2 -of GTiff orthophoto.ecw orthophoto.tif

# pyramids
gdaladdo -r average -ro --config COMPRESS_OVERVIEW JPEG --config JPEG_QUALITY_OVERVIEW 60--config INTERLEAVE_OVERVIEW PIXEL --config PHOTOMETRIC_OVERVIEW YCBCR --config TILED_OVERVIEW YES --config GDAL_TIFF_OVR_BLOCKSIZE 512 --config BIGTIFF_OVERVIEW YES --config GDAL_CACHEMAX 500 --config GDAL_MAX_DATASET_POOL_SIZE 1014 -co NUM_THREADS=2 orthophoto.tif 2 4 8 16 32 64 128 256
```

The output Geotiff is exactly what I expected, but with this `-b 1 -b 2 -b 3 -mask 4` technique, I have four files:
`orthophoto.tif, orthophoto.tif.ovr, orthophoto.tif.msk, orthophoto.tif.msk.ovr`

Then I wanted to use cogger with
```
./cogger -output orthophoto.cog.tif orthophoto.tif orthophoto.tif.ovr
```

I get the expected `orthophoto.cog.tif` file, but the mask has not been "integrated" into the cog, so I get the black rectangle around the data, for example when viewing this COG file inside QGIS.

Do I need to create a new COG file from the `orthophoto.tif.msk` and `orthophoto.tif.msk.ovr` files, or is there a better way ?

**Comment by tbonfort** [comment]
the easiest way is to rerun gdal_translate with GDAL_TIFF_INTERNAL_MASK=yes (https://gdal.org/drivers/raster/gtiff.html#internal-nodata-masks) and gdaladdo without -ro (probably with the same internal mask config option). I don't think the cogger binary is wired up to handle external masks yet.

**Comment by mdouchin** [comment]
Thanks a lot for you answer. I will try ASAP and report progress here
