### ISSUE TITLE
ENH idea: emit header ghost area and tile header and trailer bytes

### ISSUE THREAD

**Issue by rouault** [airbusgeo/cogger#2]
For really huge COGs (let's say 1 million pixel x 1 million pixel), the size of the TileByteCount and TileOffsets values can be quite big (several tens of MB). If one knows that the tiles are ordered in a top-to-bottom, left-to-right order in the file, then a smart reader can possibly only use TileOffsets, and that's what GDAL does, to save a GET request.  To do so, one must write the header ghost area per https://gdal.org/drivers/raster/cog.html#header-ghost-area and add a 4-byte header before each tile data and a 4-byte trailer after it (https://gdal.org/drivers/raster/cog.html#tile-data-leader-and-trailer), whose purpose is to check that a writer hasn't modified tile content since the COG generation, which would make the optimization no longer valid.

**Comment by tbonfort** [comment]
This might be something we could add. However this would be limited to only certain types of files, as in the presence of masks we interlace the mask tiles with the data tiles.

**Comment by rouault** [comment]
> as in the presence of masks we interlace the mask tiles with the data tiles.

that's what the GDAL COG driver also does. The tile header/trailer bytes are compatible of that pattern. See the note about that in https://gdal.org/drivers/raster/cog.html#tile-data-leader-and-trailer

**Comment by tbonfort** [comment]
do I understand correctly that in the interlaced mask case, for a given tile gdal will emit 2 read requests, one (for the pixels) of length 4+pixel_len+4+4+mask_len+4 , and one (for the mask) of length 4+mask_len+4+4+pixel_len_of_next_tile+4 ? or is it clever enough to reuse-use the data from the first request to populate the mask data?

**Comment by rouault** [comment]
> or is it clever enough to reuse-use the data from the first request to populate the mask data?

Yes, it will issue just one GET range request for the RGB tile + corresponding mask tile. This is around 
https://github.com/OSGeo/gdal/blob/e635362bb1a3c517489cc4d09fe2a41f0869c199/gdal/frmts/gtiff/geotiff.cpp#L4132 and below.

**Comment by tbonfort** [comment]
nice! I see no reason as to why this shouldn't be added then. As we cannot change the API for compatibility reasons, an implementation of this would need to decide to either make this the default behavior, or expose a new `RewriteGDALFlavored()` method

**Comment by tbonfort** [comment]
draft implementation added in #5 . @rouault is there a tool to validate/check these cog+ghost files ?

**Comment by rouault** [comment]
> is there a tool to validate/check these cog+ghost files ?

https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/gdal-utils/osgeo_utils/samples/validate_cloud_optimized_geotiff.py is aware of the ghost areas and validates the content of the leader and trailer bytes

**Comment by tbonfort** [comment]
implemented in #5
