### ISSUE TITLE
Overviews: optional or not?

### ISSUE THREAD

**Issue by maphew** [airbusgeo/cogger#3]
The read me says both _"internally tiled geotiff (optionally with overviews"_  and _"it should contain overviews"_. The statements are at odds with each other. Which is the more correct meaning?

**Comment by tbonfort** [comment]
SHOULD is to be interpreted in the context of RFC 2119: https://datatracker.ietf.org/doc/html/rfc2119 . i.e. always use overviews unless you know why you don't need them.

**Comment by Jean-Roc** [comment]
hi @tbonfort, maybe you should add a precision telling that it **internal** overview are required as multilevel & external .ovr can't be used

**Comment by tbonfort** [comment]
Instead of a documentation issue, #6 has been added to support external overviews:

`cogger -output cog.tif myfile.tif myfile.tif.ovr`

**Comment by tbonfort** [comment]
closed with #6
